[[Qt6ShaderTools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aad5a12a54d09948b34d5630fe3023bbfbaf0206"
libc = "musl"
os = "linux"

    [[Qt6ShaderTools.download]]
    sha256 = "290e484b9986b9c442b10f953cc5a6d7bb4ac1c09863d1d37d3a88a54d8830a5"
    url = "https://github.com/JuliaBinaryWrappers/Qt6ShaderTools_jll.jl/releases/download/Qt6ShaderTools-v6.10.2+0/Qt6ShaderTools.v6.10.2.x86_64-linux-musl-cxx11.tar.gz"
